// frontend/src/app/auth/reset-password/reset-password.component.ts
import { Component, inject, signal, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators, AbstractControl } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { environment } from '../../../environments/environment';

interface ApiError {
  success: false;
  message: string;
  details?: { field: string; message: string }[];
}

interface ApiSuccess {
  success: true;
  data: { message: string };
}

function passwordMatchValidator(group: AbstractControl): { mismatch: true } | null {
  const pw = group.get('newPassword')?.value as string;
  const cpw = group.get('confirmPassword')?.value as string;
  return pw === cpw ? null : { mismatch: true };
}

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, CommonModule],
  templateUrl: './reset-password.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ResetPasswordComponent implements OnInit {
  private fb = inject(FormBuilder);
  private http = inject(HttpClient);
  private route = inject(ActivatedRoute);
  private router = inject(Router);

  token = signal<string | null>(null);
  serverError = signal('');
  invalidLink = signal(false);
  loading = signal(false);

  form = this.fb.nonNullable.group(
    {
      newPassword: ['', [Validators.required, Validators.minLength(8)]],
      confirmPassword: ['', [Validators.required]]
    },
    { validators: passwordMatchValidator }
  );

  ngOnInit(): void {
    const t = this.route.snapshot.queryParamMap.get('token');
    if (!t) {
      this.invalidLink.set(true);
      return;
    }
    this.token.set(t);
  }

  submit(): void {
    if (this.form.invalid || !this.token()) {
      this.form.markAllAsTouched();
      return;
    }
    this.loading.set(true);
    this.serverError.set('');
    const payload = {
      token: this.token() as string,
      newPassword: this.form.getRawValue().newPassword
    };
    this.http
      .post<ApiSuccess>(`${environment.apiUrl}/api/auth/reset-password`, payload)
      .subscribe({
        next: () => {
          this.loading.set(false);
          this.router.navigate(['/login'], { queryParams: { reset: 'success' } });
        },
        error: (err: { error: ApiError }) => {
          this.loading.set(false);
          const details = err.error?.details ?? [];
          details.forEach((d) => {
            const ctrl = this.form.get(d.field);
            if (ctrl) {
              ctrl.setErrors({ serverError: d.message });
            }
          });
          if (!details.length) {
            this.serverError.set(err.error?.message ?? 'An error occurred. Please try again.');
          }
        }
      });
  }
}

<div class="min-h-screen flex items-center justify-center bg-slate-50">
  <div class="bg-white p-8 rounded-lg shadow w-full max-w-md">
    <h2 class="text-2xl font-bold mb-6 text-slate-800">Reset Password</h2>

    @if (invalidLink()) {
      <div class="bg-rose-50 border border-rose-300 text-rose-700 rounded p-4 mb-4">
        Invalid or missing reset link. Please request a new one.
      </div>
      <p class="mt-4 text-sm">
        <a routerLink="/forgot-password" class="text-brand-600 hover:underline">Request new link</a>
      </p>
    } @else {
      @if (serverError()) {
        <div class="bg-rose-50 border border-rose-300 text-rose-700 rounded p-3 mb-4 text-sm">
          {{ serverError() }}
        </div>
      }

      <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
        <div class="mb-4">
          <label for="rp-newPassword" class="form-label">New Password</label>
          <input
            id="rp-newPassword"
            formControlName="newPassword"
            type="password"
            autocomplete="new-password"
            class="form-input"
            placeholder="At least 8 characters, include a number"
          />
          @if (form.get('newPassword')?.invalid && form.get('newPassword')?.touched) {
            <p class="form-error">
              @if (form.get('newPassword')?.errors?.['required']) {
                Password is required.
              }
              @if (form.get('newPassword')?.errors?.['minlength']) {
                Password must be at least 8 characters long.
              }
              @if (form.get('newPassword')?.errors?.['serverError']) {
                {{ form.get('newPassword')?.errors?.['serverError'] }}
              }
            </p>
          }
        </div>

        <div class="mb-6">
          <label for="rp-confirmPassword" class="form-label">Confirm Password</label>
          <input
            id="rp-confirmPassword"
            formControlName="confirmPassword"
            type="password"
            autocomplete="new-password"
            class="form-input"
            placeholder="Repeat your new password"
          />
          @if (form.get('confirmPassword')?.touched) {
            @if (form.errors?.['mismatch'] && !form.get('confirmPassword')?.errors?.['required']) {
              <p class="form-error">Passwords do not match.</p>
            }
            @if (form.get('confirmPassword')?.errors?.['required']) {
              <p class="form-error">Please confirm your password.</p>
            }
            @if (form.get('confirmPassword')?.errors?.['serverError']) {
              <p class="form-error">{{ form.get('confirmPassword')?.errors?.['serverError'] }}</p>
            }
          }
        </div>

        <button
          type="submit"
          class="btn btn-primary w-full"
          [disabled]="loading()"
        >
          @if (loading()) {
            Resetting...
          } @else {
            Reset Password
          }
        </button>
      </form>

      <p class="mt-4 text-sm text-center">
        <a routerLink="/login" class="text-brand-600 hover:underline">Back to Login</a>
      </p>
    }
  </div>
</div>

// frontend/src/app/(auth)/reset-password/page.tsx
'use client';

import { Suspense, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation } from '@tanstack/react-query';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { toast } from 'sonner';
import { apiClient, ApiError } from '@/lib/api-client';

const resetPasswordSchema = z
  .object({
    newPassword: z.string().min(8, 'Password must be at least 8 characters'),
    confirmPassword: z.string().min(1, 'Please confirm your password'),
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

type ResetPasswordForm = z.infer<typeof resetPasswordSchema>;

function ResetPasswordInner() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const token = searchParams.get('token');
  const [tokenError, setTokenError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<ResetPasswordForm>({
    resolver: zodResolver(resetPasswordSchema),
    defaultValues: { newPassword: '', confirmPassword: '' },
  });

  const mutation = useMutation({
    mutationFn: async (data: ResetPasswordForm) => {
      return apiClient.post('/api/auth/reset-password', {
        token,
        newPassword: data.newPassword,
      });
    },
    onSuccess: () => {
      toast.success('Password reset successfully. Please sign in with your new password.');
      router.push('/login');
    },
    onError: (error: unknown) => {
      const err = error as ApiError | { status?: number; message?: string };
      const status = (err as { status?: number })?.status;
      if (status === 400 || status === 410) {
        setTokenError(
          'This reset link is invalid or has expired. Request a new one.'
        );
      } else {
        toast.error('Unable to reset password. Please try again.');
      }
    },
  });

  if (!token) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4 py-12">
        <div className="w-full max-w-md">
          <div className="bg-white rounded-lg shadow-md p-8 text-center">
            <h1 className="text-2xl font-bold text-gray-900">Invalid link</h1>
            <p className="mt-2 text-sm text-gray-600">
              This password reset link is missing a token or is malformed.
            </p>
            <Link
              href="/forgot-password"
              className="mt-6 inline-block font-medium text-indigo-600 hover:text-indigo-500"
            >
              Request a new reset link
            </Link>
          </div>
        </div>
      </div>
    );
  }

  const onSubmit = (data: ResetPasswordForm) => {
    setTokenError(null);
    mutation.mutate(data);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4 py-12">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-lg shadow-md p-8">
          <div className="mb-6 text-center">
            <h1 className="text-2xl font-bold text-gray-900">Reset your password</h1>
            <p className="mt-2 text-sm text-gray-600">
              Choose a new password for your account.
            </p>
          </div>

          {tokenError && (
            <div
              role="alert"
              className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700"
            >
              <p>{tokenError}</p>
              <Link
                href="/forgot-password"
                className="mt-2 inline-block font-medium text-red-800 underline hover:text-red-900"
              >
                Request a new reset link
              </Link>
            </div>
          )}

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4" noValidate>
            <div>
              <label
                htmlFor="newPassword"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                New password
              </label>
              <input
                id="newPassword"
                type="password"
                autoComplete="new-password"
                aria-invalid={!!errors.newPassword}
                aria-describedby={errors.newPassword ? 'newPassword-error' : undefined}
                disabled={mutation.isPending}
                {...register('newPassword')}
                className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
              />
              {errors.newPassword && (
                <p
                  id="newPassword-error"
                  role="alert"
                  className="mt-1 text-sm text-red-600"
                >
                  {errors.newPassword.message}
                </p>
              )}
            </div>

            <div>
              <label
                htmlFor="confirmPassword"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Confirm password
              </label>
              <input
                id="confirmPassword"
                type="password"
                autoComplete="new-password"
                aria-invalid={!!errors.confirmPassword}
                aria-describedby={
                  errors.confirmPassword ? 'confirmPassword-error' : undefined
                }
                disabled={mutation.isPending}
                {...register('confirmPassword')}
                className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
              />
              {errors.confirmPassword && (
                <p
                  id="confirmPassword-error"
                  role="alert"
                  className="mt-1 text-sm text-red-600"
                >
                  {errors.confirmPassword.message}
                </p>
              )}
            </div>

            <button
              type="submit"
              disabled={mutation.isPending}
              aria-busy={mutation.isPending}
              className="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {mutation.isPending ? 'Resetting…' : 'Reset password'}
            </button>
          </form>

          <div className="mt-6 text-center text-sm">
            <Link
              href="/login"
              className="font-medium text-indigo-600 hover:text-indigo-500"
            >
              Back to sign in
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ResetPasswordPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <div className="text-sm text-gray-500">Loading…</div>
        </div>
      }
    >
      <ResetPasswordInner />
    </Suspense>
  );
}
