// frontend/src/app/(auth)/login/page.tsx
'use client';

import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/stores/auth-store';
import { apiClient } from '@/lib/api-client';
import SocialLoginButtons from '@/components/auth/SocialLoginButtons';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(1, 'Password is required'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

export default function LoginPage() {
  const router = useRouter();
  const setAuth = useAuthStore((s) => s.setAuth);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    setError,
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  const onSubmit = async (values: LoginFormValues) => {
    try {
      const data = await apiClient.post<{ accessToken: string; user: Record<string, unknown> }>(
        '/auth/login',
        values
      );
      setAuth({ accessToken: data.accessToken, user: data.user });
      router.push('/dashboard');
    } catch (err: unknown) {
      const message =
        err instanceof Error ? err.message : 'Invalid email or password. Please try again.';
      setError('root', { message });
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-slate-50 px-4 py-12'>
      <div className='w-full max-w-md'>
        {/* Header */}
        <div className='text-center mb-8'>
          <h1 className='text-2xl font-bold text-brand-700'>Sign In</h1>
          <p className='mt-2 text-sm text-slate-500'>Welcome back — sign in to your account</p>
        </div>

        {/* Card */}
        <div className='card bg-white shadow-sm rounded-xl p-8'>
          <form onSubmit={handleSubmit(onSubmit)} noValidate>
            {/* Root / server error */}
            {errors.root && (
              <div
                className='mb-4 rounded-lg bg-rose-50 border border-rose-200 p-3'
                role='alert'
                aria-live='polite'
              >
                <p className='text-sm text-rose-700'>{errors.root.message}</p>
              </div>
            )}

            {/* Email field */}
            <div className='mb-4'>
              <label htmlFor='email' className='form-label block text-sm font-medium text-slate-700 mb-1'>
                Email address
              </label>
              <input
                id='email'
                type='email'
                autoComplete='email'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.email
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='you@example.com'
                {...register('email')}
              />
              {errors.email && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* Password field */}
            <div className='mb-2'>
              <div className='flex items-center justify-between mb-1'>
                <label
                  htmlFor='password'
                  className='form-label block text-sm font-medium text-slate-700'
                >
                  Password
                </label>
                <Link
                  href='/forgot-password'
                  className='text-xs text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
                >
                  Forgot password?
                </Link>
              </div>
              <input
                id='password'
                type='password'
                autoComplete='current-password'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.password
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='Enter your password'
                {...register('password')}
              />
              {errors.password && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.password.message}
                </p>
              )}
            </div>

            {/* Submit button */}
            <div className='mt-6'>
              <button
                type='submit'
                disabled={isSubmitting}
                className='btn-primary w-full rounded-lg py-2.5 px-4 text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 transition-colors duration-150 disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2'
              >
                {isSubmitting ? (
                  <>
                    <svg
                      className='animate-spin h-4 w-4 text-white'
                      xmlns='http://www.w3.org/2000/svg'
                      fill='none'
                      viewBox='0 0 24 24'
                      aria-hidden='true'
                    >
                      <circle
                        className='opacity-25'
                        cx='12'
                        cy='12'
                        r='10'
                        stroke='currentColor'
                        strokeWidth='4'
                      />
                      <path
                        className='opacity-75'
                        fill='currentColor'
                        d='M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z'
                      />
                    </svg>
                    Signing in...
                  </>
                ) : (
                  'Sign In'
                )}
              </button>
            </div>

            {/* Social login buttons — below submit, above sign-up link */}
            <SocialLoginButtons />
          </form>

          {/* Footer sign-up link */}
          <p className='mt-6 text-center text-sm text-slate-500'>
            Don&apos;t have an account?{' '}
            <Link
              href='/register'
              className='font-medium text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
            >
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/pages/login/login.component.ts
import {
  Component,
  inject,
  signal,
  computed,
  OnInit,
  ChangeDetectionStrategy
} from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { Router, RouterLink, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, CommonModule],
  templateUrl: './login.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class LoginComponent implements OnInit {
  private fb = inject(FormBuilder);
  private auth = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  serverError = signal('');
  loading = signal(false);
  resetSuccess = signal(false);

  form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]]
  });

  ngOnInit(): void {
    const reset = this.route.snapshot.queryParamMap.get('reset');
    if (reset === 'success') {
      this.resetSuccess.set(true);
    }
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.loading.set(true);
    this.serverError.set('');
    const { email, password } = this.form.getRawValue();
    this.auth.login(email, password).subscribe({
      next: () => {
        this.loading.set(false);
        this.router.navigate(['/dashboard']);
      },
      error: (err: { error: { message?: string; details?: { field: string; message: string }[] } }) => {
        this.loading.set(false);
        const details = err.error?.details ?? [];
        details.forEach((d) => {
          const ctrl = this.form.get(d.field);
          if (ctrl) {
            ctrl.setErrors({ serverError: d.message });
          }
        });
        if (!details.length) {
          this.serverError.set(err.error?.message ?? 'Login failed. Please try again.');
        }
      }
    });
  }
}

<div class="min-h-screen flex items-center justify-center bg-slate-50">
  <div class="bg-white p-8 rounded-lg shadow w-full max-w-md">
    <h2 class="text-2xl font-bold mb-2 text-slate-800">Sign in</h2>
    <p class="text-sm text-slate-500 mb-6">Welcome back. Please enter your details.</p>

    @if (resetSuccess()) {
      <div class="bg-green-50 border border-green-300 text-green-700 rounded p-3 mb-4 text-sm">
        Password reset successfully. Please log in with your new password.
      </div>
    }

    @if (serverError()) {
      <div class="bg-rose-50 border border-rose-300 text-rose-700 rounded p-3 mb-4 text-sm">
        {{ serverError() }}
      </div>
    }

    <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
      <div class="mb-4">
        <label for="login-email" class="form-label">Email address</label>
        <input
          id="login-email"
          formControlName="email"
          type="email"
          autocomplete="email"
          class="form-input"
          placeholder="you@example.com"
        />
        @if (form.get('email')?.invalid && form.get('email')?.touched) {
          <p class="form-error">
            @if (form.get('email')?.errors?.['required']) {
              Email is required.
            }
            @if (form.get('email')?.errors?.['email']) {
              Enter a valid email address.
            }
            @if (form.get('email')?.errors?.['serverError']) {
              {{ form.get('email')?.errors?.['serverError'] }}
            }
          </p>
        }
      </div>

      <div class="mb-2">
        <label for="login-password" class="form-label">Password</label>
        <input
          id="login-password"
          formControlName="password"
          type="password"
          autocomplete="current-password"
          class="form-input"
          placeholder="••••••••"
        />
        @if (form.get('password')?.invalid && form.get('password')?.touched) {
          <p class="form-error">
            @if (form.get('password')?.errors?.['required']) {
              Password is required.
            }
            @if (form.get('password')?.errors?.['serverError']) {
              {{ form.get('password')?.errors?.['serverError'] }}
            }
          </p>
        }
      </div>

      <div class="flex justify-end mb-6">
        <a routerLink="/forgot-password" class="text-sm text-brand-600 hover:underline">Forgot Password?</a>
      </div>

      <button
        type="submit"
        class="btn btn-primary w-full"
        [disabled]="loading()"
      >
        @if (loading()) {
          Signing in...
        } @else {
          Sign in
        }
      </button>
    </form>

    <p class="mt-4 text-sm text-center text-slate-600">
      Don't have an account?
      <a routerLink="/register" class="text-brand-600 hover:underline">Sign up</a>
    </p>
  </div>
</div>
