// frontend/src/app/(auth)/login/page.tsx
'use client';

import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/stores/auth-store';
import { apiClient } from '@/lib/api-client';
import SocialLoginButtons from '@/components/auth/SocialLoginButtons';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(1, 'Password is required'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

export default function LoginPage() {
  const router = useRouter();
  const setAuth = useAuthStore((s) => s.setAuth);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    setError,
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  const onSubmit = async (values: LoginFormValues) => {
    try {
      const data = await apiClient.post<{ accessToken: string; user: Record<string, unknown> }>(
        '/auth/login',
        values
      );
      setAuth({ accessToken: data.accessToken, user: data.user });
      router.push('/dashboard');
    } catch (err: unknown) {
      const message =
        err instanceof Error ? err.message : 'Invalid email or password. Please try again.';
      setError('root', { message });
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-slate-50 px-4 py-12'>
      <div className='w-full max-w-md'>
        {/* Header */}
        <div className='text-center mb-8'>
          <h1 className='text-2xl font-bold text-brand-700'>Sign In</h1>
          <p className='mt-2 text-sm text-slate-500'>Welcome back — sign in to your account</p>
        </div>

        {/* Card */}
        <div className='card bg-white shadow-sm rounded-xl p-8'>
          <form onSubmit={handleSubmit(onSubmit)} noValidate>
            {/* Root / server error */}
            {errors.root && (
              <div
                className='mb-4 rounded-lg bg-rose-50 border border-rose-200 p-3'
                role='alert'
                aria-live='polite'
              >
                <p className='text-sm text-rose-700'>{errors.root.message}</p>
              </div>
            )}

            {/* Email field */}
            <div className='mb-4'>
              <label htmlFor='email' className='form-label block text-sm font-medium text-slate-700 mb-1'>
                Email address
              </label>
              <input
                id='email'
                type='email'
                autoComplete='email'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.email
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='you@example.com'
                {...register('email')}
              />
              {errors.email && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* Password field */}
            <div className='mb-2'>
              <div className='flex items-center justify-between mb-1'>
                <label
                  htmlFor='password'
                  className='form-label block text-sm font-medium text-slate-700'
                >
                  Password
                </label>
                <Link
                  href='/forgot-password'
                  className='text-xs text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
                >
                  Forgot password?
                </Link>
              </div>
              <input
                id='password'
                type='password'
                autoComplete='current-password'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.password
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='Enter your password'
                {...register('password')}
              />
              {errors.password && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.password.message}
                </p>
              )}
            </div>

            {/* Submit button */}
            <div className='mt-6'>
              <button
                type='submit'
                disabled={isSubmitting}
                className='btn-primary w-full rounded-lg py-2.5 px-4 text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 transition-colors duration-150 disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2'
              >
                {isSubmitting ? (
                  <>
                    <svg
                      className='animate-spin h-4 w-4 text-white'
                      xmlns='http://www.w3.org/2000/svg'
                      fill='none'
                      viewBox='0 0 24 24'
                      aria-hidden='true'
                    >
                      <circle
                        className='opacity-25'
                        cx='12'
                        cy='12'
                        r='10'
                        stroke='currentColor'
                        strokeWidth='4'
                      />
                      <path
                        className='opacity-75'
                        fill='currentColor'
                        d='M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z'
                      />
                    </svg>
                    Signing in...
                  </>
                ) : (
                  'Sign In'
                )}
              </button>
            </div>

            {/* Social login buttons — below submit, above sign-up link */}
            <SocialLoginButtons />
          </form>

          {/* Footer sign-up link */}
          <p className='mt-6 text-center text-sm text-slate-500'>
            Don&apos;t have an account?{' '}
            <Link
              href='/register'
              className='font-medium text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
            >
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/pages/auth/login/login.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule, MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import { AuthService } from '../../../core/services/auth.service';
import { LoginPayload } from '../../../core/models/auth.model';

@Component({
  selector: 'app-login',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterLink,
    MatButtonModule,
    MatIconModule
  ],
  templateUrl: './login.component.html'
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly matIconRegistry = inject(MatIconRegistry);
  private readonly domSanitizer = inject(DomSanitizer);

  readonly isLoading = signal(false);
  readonly globalError = signal<string | null>(null);

  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  });

  constructor() {
    this.matIconRegistry.addSvgIconLiteral(
      'google',
      this.domSanitizer.bypassSecurityTrustHtml(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path fill="#EA4335" d="M24 9.5c3.14 0 5.95 1.08 8.17 2.84l6.09-6.09C34.46 3.39 29.5 1.5 24 1.5 14.82 1.5 7.01 7.1 3.64 15.01l7.08 5.5C12.4 14.09 17.73 9.5 24 9.5z"/><path fill="#4285F4" d="M46.15 24.5c0-1.57-.14-3.09-.4-4.55H24v8.61h12.44c-.54 2.9-2.18 5.36-4.64 7.01l7.1 5.52C42.99 37.36 46.15 31.36 46.15 24.5z"/><path fill="#FBBC05" d="M10.72 28.51A14.55 14.55 0 0 1 9.5 24c0-1.57.27-3.09.72-4.51l-7.08-5.5A22.47 22.47 0 0 0 1.5 24c0 3.61.86 7.02 2.64 10.01l6.58-5.5z"/><path fill="#34A853" d="M24 46.5c5.5 0 10.13-1.82 13.5-4.94l-7.1-5.52c-1.82 1.22-4.15 1.96-6.4 1.96-6.27 0-11.6-4.59-13.28-10.99l-6.58 5.5C7.01 40.9 14.82 46.5 24 46.5z"/><path fill="none" d="M1.5 1.5h45v45h-45z"/></svg>'
      )
    );

    this.matIconRegistry.addSvgIconLiteral(
      'facebook',
      this.domSanitizer.bypassSecurityTrustHtml(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path fill="#1877F2" d="M48 24C48 10.74 37.26 0 24 0S0 10.74 0 24c0 11.98 8.77 21.9 20.25 23.71V30.94h-6.09V24h6.09v-5.29c0-6.02 3.58-9.34 9.07-9.34 2.63 0 5.38.47 5.38.47v5.92h-3.03c-2.98 0-3.91 1.85-3.91 3.75V24h6.66l-1.06 6.94H27.76v16.77C39.23 45.9 48 35.98 48 24z"/><path fill="#fff" d="M33.36 30.94l1.06-6.94h-6.66v-4.49c0-1.9.93-3.75 3.91-3.75h3.03v-5.92s-2.75-.47-5.38-.47c-5.49 0-9.07 3.32-9.07 9.34V24h-6.09v6.94h6.09v16.77a24.14 24.14 0 0 0 7.5 0V30.94h5.61z"/></svg>'
      )
    );
  }

  onSocialLoginClick(provider: string): void {
    /* placeholder — no logic yet */
  }

  get emailControl() {
    return this.form.controls.email;
  }

  get passwordControl() {
    return this.form.controls.password;
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.isLoading.set(true);
    this.globalError.set(null);

    const payload: LoginPayload = this.form.getRawValue();

    this.auth.login(payload).subscribe({
      next: () => {
        this.isLoading.set(false);
        this.router.navigate(['/dashboard']);
      },
      error: (err: { message?: string; details?: Array<{ field: string; message: string }> }) => {
        this.isLoading.set(false);
        this.globalError.set(err.message ?? 'Login failed. Please try again.');

        if (err.details && Array.isArray(err.details)) {
          for (const detail of err.details) {
            const control = this.form.get(detail.field);
            if (control) {
              control.setErrors({ serverError: detail.message });
            }
          }
        }
      }
    });
  }
}

<div class="card max-w-md mx-auto px-4">
  <h1 class="text-2xl font-bold text-slate-900 mb-6 text-center">Sign In</h1>

  <!-- Social Login Buttons -->
  <div class="flex gap-3 justify-center mt-2 flex-col sm:flex-row">
    <button
      mat-stroked-button
      type="button"
      class="flex items-center gap-2 px-4 py-2 w-full justify-center"
      aria-label="Sign in with Google"
      (click)="onSocialLoginClick('google')"
    >
      <mat-icon svgIcon="google" class="!w-5 !h-5"></mat-icon>
      <span class="text-sm font-medium text-slate-900">Google</span>
    </button>

    <button
      mat-stroked-button
      type="button"
      class="flex items-center gap-2 px-4 py-2 w-full justify-center"
      aria-label="Sign in with Facebook"
      (click)="onSocialLoginClick('facebook')"
    >
      <mat-icon svgIcon="facebook" class="!w-5 !h-5"></mat-icon>
      <span class="text-sm font-medium text-slate-900">Facebook</span>
    </button>
  </div>

  <!-- Divider -->
  <div class="flex items-center my-4">
    <div class="flex-1 border-t border-gray-300"></div>
    <span class="mx-3 text-sm text-gray-500">or continue with</span>
    <div class="flex-1 border-t border-gray-300"></div>
  </div>

  <!-- Global Error -->
  @if (globalError()) {
    <div class="mb-4 rounded-md bg-rose-50 border border-rose-300 px-4 py-3">
      <p class="text-sm text-rose-700">{{ globalError() }}</p>
    </div>
  }

  <!-- Email/Password Form -->
  <form [formGroup]="form" (ngSubmit)="onSubmit()" novalidate>
    <!-- Email Field -->
    <div class="mb-4">
      <label for="email" class="form-label">Email address</label>
      <input
        id="email"
        type="email"
        formControlName="email"
        class="form-input"
        autocomplete="email"
        placeholder="you@example.com"
      />
      @if (emailControl.touched && emailControl.errors) {
        @if (emailControl.errors['required']) {
          <p class="form-error">Email is required.</p>
        } @else if (emailControl.errors['email']) {
          <p class="form-error">Please enter a valid email address.</p>
        } @else if (emailControl.errors['serverError']) {
          <p class="form-error">{{ emailControl.errors['serverError'] }}</p>
        }
      }
    </div>

    <!-- Password Field -->
    <div class="mb-6">
      <label for="password" class="form-label">Password</label>
      <input
        id="password"
        type="password"
        formControlName="password"
        class="form-input"
        autocomplete="current-password"
        placeholder="••••••••"
      />
      @if (passwordControl.touched && passwordControl.errors) {
        @if (passwordControl.errors['required']) {
          <p class="form-error">Password is required.</p>
        } @else if (passwordControl.errors['minlength']) {
          <p class="form-error">Password must be at least 6 characters.</p>
        } @else if (passwordControl.errors['serverError']) {
          <p class="form-error">{{ passwordControl.errors['serverError'] }}</p>
        }
      }
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      class="btn btn-primary w-full"
      [disabled]="isLoading()"
    >
      @if (isLoading()) {
        <span>Signing in...</span>
      } @else {
        <span>Sign In</span>
      }
    </button>
  </form>

  <!-- Footer Links -->
  <div class="mt-4 text-center text-sm text-slate-600">
    <span>Don't have an account?</span>
    <a routerLink="/auth/register" class="btn-ghost ml-1 text-sm">Sign up</a>
  </div>
</div>
