// frontend/src/app/(auth)/forgot-password/page.tsx
'use client';

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation } from '@tanstack/react-query';
import Link from 'next/link';
import { toast } from 'sonner';
import { apiClient } from '@/lib/api-client';

const forgotPasswordSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
});

type ForgotPasswordForm = z.infer<typeof forgotPasswordSchema>;

export default function ForgotPasswordPage() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<ForgotPasswordForm>({
    resolver: zodResolver(forgotPasswordSchema),
    defaultValues: { email: '' },
  });

  const mutation = useMutation({
    mutationFn: async (data: ForgotPasswordForm) => {
      return apiClient.post('/api/auth/forgot-password', { email: data.email });
    },
    onSettled: () => {
      toast.success(
        'If an account exists for that email, a reset link has been sent.'
      );
    },
  });

  const onSubmit = (data: ForgotPasswordForm) => {
    mutation.mutate(data);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4 py-12">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-lg shadow-md p-8">
          <div className="mb-6 text-center">
            <h1 className="text-2xl font-bold text-gray-900">Forgot password?</h1>
            <p className="mt-2 text-sm text-gray-600">
              Enter your email and we&apos;ll send you a link to reset your password.
            </p>
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4" noValidate>
            <div>
              <label
                htmlFor="email"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Email address
              </label>
              <input
                id="email"
                type="email"
                autoComplete="email"
                aria-invalid={!!errors.email}
                aria-describedby={errors.email ? 'email-error' : undefined}
                disabled={mutation.isPending}
                {...register('email')}
                className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                placeholder="you@example.com"
              />
              {errors.email && (
                <p id="email-error" role="alert" className="mt-1 text-sm text-red-600">
                  {errors.email.message}
                </p>
              )}
            </div>

            <button
              type="submit"
              disabled={mutation.isPending}
              aria-busy={mutation.isPending}
              className="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {mutation.isPending ? 'Sending…' : 'Send reset link'}
            </button>
          </form>

          <div className="mt-6 text-center text-sm">
            <Link
              href="/login"
              className="font-medium text-indigo-600 hover:text-indigo-500"
            >
              Back to sign in
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/auth/forgot-password/forgot-password.component.ts
import { Component, inject, signal, ChangeDetectionStrategy } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

interface ApiError {
  success: false;
  message: string;
  details?: { field: string; message: string }[];
}

interface ApiSuccess {
  success: true;
  data: { message: string };
}

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, CommonModule],
  templateUrl: './forgot-password.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ForgotPasswordComponent {
  private fb = inject(FormBuilder);
  private http = inject(HttpClient);

  submitted = signal(false);
  serverError = signal('');
  loading = signal(false);

  form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]]
  });

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.loading.set(true);
    this.serverError.set('');
    const payload = { email: this.form.getRawValue().email };
    this.http
      .post<ApiSuccess>(`${environment.apiUrl}/api/auth/forgot-password`, payload)
      .subscribe({
        next: () => {
          this.loading.set(false);
          this.submitted.set(true);
        },
        error: (err: { error: ApiError }) => {
          this.loading.set(false);
          const details = err.error?.details ?? [];
          details.forEach((d) => {
            const ctrl = this.form.get(d.field);
            if (ctrl) {
              ctrl.setErrors({ serverError: d.message });
            }
          });
          if (!details.length) {
            this.serverError.set(err.error?.message ?? 'An error occurred. Please try again.');
          }
        }
      });
  }
}

<div class="min-h-screen flex items-center justify-center bg-slate-50">
  <div class="bg-white p-8 rounded-lg shadow w-full max-w-md">
    <h2 class="text-2xl font-bold mb-2 text-slate-800">Forgot Password</h2>
    <p class="text-sm text-slate-500 mb-6">Enter your email and we'll send you a reset link.</p>

    @if (submitted()) {
      <div class="bg-green-50 border border-green-300 text-green-700 rounded p-4 mb-4">
        If that email is registered, a reset link has been sent.
      </div>
      <p class="mt-4 text-sm text-center">
        <a routerLink="/login" class="text-brand-600 hover:underline">Back to Login</a>
      </p>
    } @else {
      @if (serverError()) {
        <div class="bg-rose-50 border border-rose-300 text-rose-700 rounded p-3 mb-4 text-sm">
          {{ serverError() }}
        </div>
      }

      <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
        <div class="mb-4">
          <label for="fp-email" class="form-label">Email address</label>
          <input
            id="fp-email"
            formControlName="email"
            type="email"
            autocomplete="email"
            class="form-input"
            placeholder="you@example.com"
          />
          @if (form.get('email')?.invalid && form.get('email')?.touched) {
            <p class="form-error">
              @if (form.get('email')?.errors?.['required']) {
                Email is required.
              }
              @if (form.get('email')?.errors?.['email']) {
                Enter a valid email address.
              }
              @if (form.get('email')?.errors?.['serverError']) {
                {{ form.get('email')?.errors?.['serverError'] }}
              }
            </p>
          }
        </div>

        <button
          type="submit"
          class="btn btn-primary w-full"
          [disabled]="loading()"
        >
          @if (loading()) {
            Sending...
          } @else {
            Send Reset Link
          }
        </button>
      </form>

      <p class="mt-4 text-sm text-center">
        <a routerLink="/login" class="text-brand-600 hover:underline">Back to Login</a>
      </p>
    }
  </div>
</div>
