// frontend/src/app/login/login.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  signal,
  computed,
  inject,
} from '@angular/core';
import {
  FormBuilder,
  ReactiveFormsModule,
  Validators,
  AbstractControl,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly loading = signal(false);
  readonly errorMessage = signal<string | null>(null);

  readonly loginForm = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
  });

  readonly emailError = computed(() => {
    const ctrl = this.loginForm.controls.email;
    if (ctrl.valid || ctrl.pristine) return null;
    if (ctrl.errors?.['required']) return 'Email is required.';
    if (ctrl.errors?.['email']) return 'Please enter a valid email address.';
    if (ctrl.errors?.['serverError']) return ctrl.errors['serverError'] as string;
    return null;
  });

  readonly passwordError = computed(() => {
    const ctrl = this.loginForm.controls.password;
    if (ctrl.valid || ctrl.pristine) return null;
    if (ctrl.errors?.['required']) return 'Password is required.';
    if (ctrl.errors?.['minlength']) return 'Password must be at least 6 characters.';
    if (ctrl.errors?.['serverError']) return ctrl.errors['serverError'] as string;
    return null;
  });

  ngOnInit(): void {
    if (this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
    }
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    this.loading.set(true);
    this.errorMessage.set(null);

    const { email, password } = this.loginForm.getRawValue();

    this.auth.login({ email, password }).subscribe({
      next: () => {
        this.loading.set(false);
        this.router.navigate(['/dashboard']);
      },
      error: (err: { message?: string; details?: { field: string; message: string }[] }) => {
        this.loading.set(false);
        this.errorMessage.set(err.message ?? 'Login failed. Please try again.');

        if (err.details?.length) {
          err.details.forEach((detail) => {
            const ctrl: AbstractControl | null = this.loginForm.get(detail.field);
            if (ctrl) {
              ctrl.setErrors({ serverError: detail.message });
            }
          });
        }
      },
    });
  }
}

<div class="card max-w-md mx-auto px-4">
  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" novalidate>

    <!-- Header -->
    <div class="mb-6 text-center">
      <h1 class="text-2xl font-bold text-slate-800">Welcome back</h1>
      <p class="mt-1 text-sm text-slate-500">Sign in to your account</p>
    </div>

    <!-- Global error -->
    @if (errorMessage()) {
      <div role="alert" aria-live="polite" class="mb-4 rounded-md bg-rose-50 px-4 py-3 text-sm text-rose-700">
        {{ errorMessage() }}
      </div>
    }

    <!-- Email -->
    <div class="mb-4">
      <label for="email" class="form-label">Email</label>
      <input
        id="email"
        type="email"
        class="form-input"
        formControlName="email"
        placeholder="you@example.com"
        autocomplete="email"
        aria-label="Email"
        [attr.aria-describedby]="emailError() ? 'email-error' : null"
      />
      @if (emailError()) {
        <p id="email-error" class="form-error" aria-live="polite">{{ emailError() }}</p>
      }
    </div>

    <!-- Password -->
    <div class="mb-0">
      <label for="password" class="form-label">Password</label>
      <input
        id="password"
        type="password"
        class="form-input"
        formControlName="password"
        placeholder="••••••••"
        autocomplete="current-password"
        aria-label="Password"
        [attr.aria-describedby]="passwordError() ? 'password-error' : null"
      />
      @if (passwordError()) {
        <p id="password-error" class="form-error" aria-live="polite">{{ passwordError() }}</p>
      }
    </div>

    <!-- Social Media Icons (immediately below password field) -->
    <fieldset class="mt-4">
      <legend class="sr-only">Or continue with</legend>
      <div class="flex items-center justify-center gap-3">

        <!-- Google -->
        <a
          href="#"
          aria-label="Sign in with Google"
          class="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 transition-colors hover:bg-brand-50 hover:text-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="h-5 w-5" fill="currentColor" aria-hidden="true">
            <path d="M21.805 10.023H12v3.977h5.618c-.242 1.242-.98 2.296-2.086 3.001v2.493h3.378c1.977-1.821 3.117-4.507 3.117-7.485 0-.501-.044-.988-.122-1.986z" fill="#4285F4"/>
            <path d="M12 22c2.7 0 4.963-.895 6.61-2.426l-3.378-2.493c-.894.599-2.037.952-3.232.952-2.484 0-4.588-1.678-5.342-3.932H3.179v2.573A9.997 9.997 0 0 0 12 22z" fill="#34A853"/>
            <path d="M6.658 14.101A5.973 5.973 0 0 1 6.345 12c0-.733.127-1.443.313-2.101V7.326H3.179A9.997 9.997 0 0 0 2 12c0 1.614.387 3.14 1.179 4.674l3.479-2.573z" fill="#FBBC05"/>
            <path d="M12 6.068c1.4 0 2.656.481 3.645 1.426l2.734-2.734C16.959 3.236 14.696 2.003 12 2.003A9.997 9.997 0 0 0 3.179 7.326l3.479 2.573C7.412 7.746 9.516 6.068 12 6.068z" fill="#EA4335"/>
          </svg>
        </a>

        <!-- GitHub -->
        <a
          href="#"
          aria-label="Sign in with GitHub"
          class="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-700 transition-colors hover:bg-brand-50 hover:text-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="h-5 w-5" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.009-.868-.013-1.703-2.782.604-3.369-1.342-3.369-1.342-.454-1.154-1.11-1.462-1.11-1.462-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.832.091-.647.35-1.087.636-1.337-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.578 9.578 0 0 1 12 6.836a9.59 9.59 0 0 1 2.504.337c1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.202 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.579.688.481C19.138 20.163 22 16.418 22 12c0-5.523-4.477-10-10-10z"/>
          </svg>
        </a>

        <!-- Twitter / X -->
        <a
          href="#"
          aria-label="Sign in with Twitter"
          class="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-700 transition-colors hover:bg-brand-50 hover:text-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="h-5 w-5" fill="currentColor" aria-hidden="true">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
          </svg>
        </a>

      </div>

      <p class="mt-2 text-center text-xs text-slate-400">or continue with</p>
    </fieldset>

    <!-- Submit Button -->
    <div class="mt-6">
      <button
        type="submit"
        class="btn btn-primary w-full"
        [disabled]="loading()"
        [attr.aria-busy]="loading()"
      >
        @if (loading()) {
          <span class="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" aria-hidden="true"></span>
          Signing in…
        } @else {
          Sign In
        }
      </button>
    </div>

    <!-- Footer / Secondary Actions -->
    <div class="mt-4 flex flex-col items-center gap-2 text-sm">
      <a routerLink="/forgot-password" class="btn-ghost text-slate-600 hover:text-brand-600">Forgot password?</a>
      <p class="text-slate-500">
        Don't have an account?
        <a routerLink="/register" class="font-medium text-brand-600 hover:text-brand-700 hover:underline">Sign up</a>
      </p>
    </div>

  </form>
</div>

// frontend/src/app/(auth)/login/page.tsx
'use client';

import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/stores/auth-store';
import { apiClient } from '@/lib/api-client';
import SocialLoginButtons from '@/components/auth/SocialLoginButtons';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(1, 'Password is required'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

export default function LoginPage() {
  const router = useRouter();
  const setAuth = useAuthStore((s) => s.setAuth);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    setError,
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  const onSubmit = async (values: LoginFormValues) => {
    try {
      const data = await apiClient.post<{ accessToken: string; user: Record<string, unknown> }>(
        '/auth/login',
        values
      );
      setAuth({ accessToken: data.accessToken, user: data.user });
      router.push('/dashboard');
    } catch (err: unknown) {
      const message =
        err instanceof Error ? err.message : 'Invalid email or password. Please try again.';
      setError('root', { message });
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-slate-50 px-4 py-12'>
      <div className='w-full max-w-md'>
        {/* Header */}
        <div className='text-center mb-8'>
          <h1 className='text-2xl font-bold text-brand-700'>Sign In</h1>
          <p className='mt-2 text-sm text-slate-500'>Welcome back — sign in to your account</p>
        </div>

        {/* Card */}
        <div className='card bg-white shadow-sm rounded-xl p-8'>
          <form onSubmit={handleSubmit(onSubmit)} noValidate>
            {/* Root / server error */}
            {errors.root && (
              <div
                className='mb-4 rounded-lg bg-rose-50 border border-rose-200 p-3'
                role='alert'
                aria-live='polite'
              >
                <p className='text-sm text-rose-700'>{errors.root.message}</p>
              </div>
            )}

            {/* Email field */}
            <div className='mb-4'>
              <label htmlFor='email' className='form-label block text-sm font-medium text-slate-700 mb-1'>
                Email address
              </label>
              <input
                id='email'
                type='email'
                autoComplete='email'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.email
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='you@example.com'
                {...register('email')}
              />
              {errors.email && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* Password field */}
            <div className='mb-2'>
              <div className='flex items-center justify-between mb-1'>
                <label
                  htmlFor='password'
                  className='form-label block text-sm font-medium text-slate-700'
                >
                  Password
                </label>
                <Link
                  href='/forgot-password'
                  className='text-xs text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
                >
                  Forgot password?
                </Link>
              </div>
              <input
                id='password'
                type='password'
                autoComplete='current-password'
                required
                disabled={isSubmitting}
                className={`form-input w-full rounded-lg border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-1 transition-colors ${
                  errors.password
                    ? 'border-rose-400 bg-rose-50'
                    : 'border-slate-300 bg-white hover:border-slate-400'
                } disabled:opacity-60 disabled:cursor-not-allowed`}
                placeholder='Enter your password'
                {...register('password')}
              />
              {errors.password && (
                <p className='form-error mt-1 text-xs text-rose-600' role='alert'>
                  {errors.password.message}
                </p>
              )}
            </div>

            {/* Submit button */}
            <div className='mt-6'>
              <button
                type='submit'
                disabled={isSubmitting}
                className='btn-primary w-full rounded-lg py-2.5 px-4 text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 transition-colors duration-150 disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2'
              >
                {isSubmitting ? (
                  <>
                    <svg
                      className='animate-spin h-4 w-4 text-white'
                      xmlns='http://www.w3.org/2000/svg'
                      fill='none'
                      viewBox='0 0 24 24'
                      aria-hidden='true'
                    >
                      <circle
                        className='opacity-25'
                        cx='12'
                        cy='12'
                        r='10'
                        stroke='currentColor'
                        strokeWidth='4'
                      />
                      <path
                        className='opacity-75'
                        fill='currentColor'
                        d='M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z'
                      />
                    </svg>
                    Signing in...
                  </>
                ) : (
                  'Sign In'
                )}
              </button>
            </div>

            {/* Social login buttons — below submit, above sign-up link */}
            <SocialLoginButtons />
          </form>

          {/* Footer sign-up link */}
          <p className='mt-6 text-center text-sm text-slate-500'>
            Don&apos;t have an account?{' '}
            <Link
              href='/register'
              className='font-medium text-brand-600 hover:text-brand-700 hover:underline focus:outline-none focus:ring-2 focus:ring-brand-500 rounded'
            >
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
